import {
  QuarterlyReviewAssignment,
  ReviewFormData,
  ManagerQuarterlyReviewRecord,
  AccessRequest,
} from "../types/appraisal.types";

export const initialMockQuarterlyReviewTableData: ManagerQuarterlyReviewRecord[] = [
  {
    name: "Ananya Sharma",
    id: "EMP001",
    role: "Frontend Developer",
    quarter: "Q1",
    financialYear: "FY 2026-27",
    fromDate: "01-04-2026",
    toDate: "30-06-2026",
    assignedOn: "05-04-2026",
    assignedBy: "Manager",
    finalRating: "-",
    status: "NOT_STARTED",
  },
  {
    name: "Rahul Kumar",
    id: "EMP002",
    role: "Backend Developer",
    quarter: "Q1",
    financialYear: "FY 2026-27",
    fromDate: "01-04-2026",
    toDate: "30-06-2026",
    assignedOn: "06-04-2026",
    assignedBy: "Admin",
    finalRating: "-",
    status: "IN_PROGRESS",
  },
  {
    name: "Priya N",
    id: "EMP003",
    role: "UI/UX Designer",
    quarter: "Q1",
    financialYear: "FY 2026-27",
    fromDate: "01-04-2026",
    toDate: "30-06-2026",
    assignedOn: "07-04-2026",
    assignedBy: "Manager",
    finalRating: "4.2",
    status: "COMPLETED",
  },
  {
    name: "Arjun R",
    id: "EMP004",
    role: "QA Engineer",
    quarter: "Q1",
    financialYear: "FY 2026-27",
    fromDate: "01-04-2026",
    toDate: "30-06-2026",
    assignedOn: "08-04-2026",
    assignedBy: "Manager",
    finalRating: "3.8",
    status: "SUBMITTED",
  },
  {
    name: "Sneha Gowda",
    id: "EMP005",
    role: "Full Stack Developer",
    quarter: "Q2",
    financialYear: "FY 2026-27",
    fromDate: "01-07-2026",
    toDate: "30-09-2026",
    assignedOn: "02-07-2026",
    assignedBy: "Admin",
    finalRating: "-",
    status: "NOT_STARTED",
  },
  {
    name: "Vikram Malhotra",
    id: "EMP006",
    role: "DevOps Engineer",
    quarter: "Q2",
    financialYear: "FY 2026-27",
    fromDate: "01-07-2026",
    toDate: "30-09-2026",
    assignedOn: "03-07-2026",
    assignedBy: "Manager",
    finalRating: "4.5",
    status: "COMPLETED",
  },
  {
    name: "Neha Patel",
    id: "EMP007",
    role: "Product Designer",
    quarter: "Q2",
    financialYear: "FY 2026-27",
    fromDate: "01-07-2026",
    toDate: "30-09-2026",
    assignedOn: "05-07-2026",
    assignedBy: "Admin",
    finalRating: "4.0",
    status: "SUBMITTED",
  },
  {
    name: "Karthik Sundaram",
    id: "EMP008",
    role: "Mobile Developer",
    quarter: "Q3",
    financialYear: "FY 2026-27",
    fromDate: "01-10-2026",
    toDate: "31-12-2026",
    assignedOn: "05-10-2026",
    assignedBy: "Manager",
    finalRating: "-",
    status: "IN_PROGRESS",
  },
  {
    name: "Pooja Nair",
    id: "EMP009",
    role: "Data Analyst",
    quarter: "Q3",
    financialYear: "FY 2026-27",
    fromDate: "01-10-2026",
    toDate: "31-12-2026",
    assignedOn: "06-10-2026",
    assignedBy: "Manager",
    finalRating: "4.7",
    status: "COMPLETED",
  },
  {
    name: "Rohan Mehta",
    id: "EMP010",
    role: "Cloud Architect",
    quarter: "Q3",
    financialYear: "FY 2026-27",
    fromDate: "01-10-2026",
    toDate: "31-12-2026",
    assignedOn: "08-10-2026",
    assignedBy: "Admin",
    finalRating: "-",
    status: "NOT_STARTED",
  },
  {
    name: "Divya Krishnan",
    id: "EMP011",
    role: "Frontend Developer",
    quarter: "Q4",
    financialYear: "FY 2026-27",
    fromDate: "01-01-2027",
    toDate: "31-03-2027",
    assignedOn: "04-01-2027",
    assignedBy: "Manager",
    finalRating: "3.9",
    status: "SUBMITTED",
  },
  {
    name: "Amit Joshi",
    id: "EMP012",
    role: "Security Engineer",
    quarter: "Q4",
    financialYear: "FY 2026-27",
    fromDate: "01-01-2027",
    toDate: "31-03-2027",
    assignedOn: "05-01-2027",
    assignedBy: "Manager",
    finalRating: "-",
    status: "IN_PROGRESS",
  },
  {
    name: "Meera Reddy",
    id: "EMP013",
    role: "UI/UX Designer",
    quarter: "Q1",
    financialYear: "FY 2026-27",
    fromDate: "01-04-2026",
    toDate: "30-06-2026",
    assignedOn: "08-04-2026",
    assignedBy: "Manager",
    finalRating: "4.6",
    status: "COMPLETED",
  },
  {
    name: "Siddharth Rao",
    id: "EMP014",
    role: "Full Stack Developer",
    quarter: "Q1",
    financialYear: "FY 2026-27",
    fromDate: "01-04-2026",
    toDate: "30-06-2026",
    assignedOn: "10-04-2026",
    assignedBy: "Admin",
    finalRating: "-",
    status: "NOT_STARTED",
  },
  {
    name: "Tanvi Kapoor",
    id: "EMP015",
    role: "QA Automation Engineer",
    quarter: "Q2",
    financialYear: "FY 2026-27",
    fromDate: "01-07-2026",
    toDate: "30-09-2026",
    assignedOn: "04-07-2026",
    assignedBy: "Manager",
    finalRating: "4.1",
    status: "SUBMITTED",
  },
  {
    name: "Harsh Vardhan",
    id: "EMP016",
    role: "Backend Architect",
    quarter: "Q2",
    financialYear: "FY 2026-27",
    fromDate: "01-07-2026",
    toDate: "30-09-2026",
    assignedOn: "06-07-2026",
    assignedBy: "Manager",
    finalRating: "-",
    status: "IN_PROGRESS",
  },
  {
    name: "Aakash Gupta",
    id: "EMP017",
    role: "DevOps Specialist",
    quarter: "Q2",
    financialYear: "FY 2026-27",
    fromDate: "01-07-2026",
    toDate: "30-09-2026",
    assignedOn: "09-07-2026",
    assignedBy: "Admin",
    finalRating: "4.4",
    status: "COMPLETED",
  },
  {
    name: "Ishita Sen",
    id: "EMP018",
    role: "Frontend Engineer",
    quarter: "Q3",
    financialYear: "FY 2026-27",
    fromDate: "01-10-2026",
    toDate: "31-12-2026",
    assignedOn: "07-10-2026",
    assignedBy: "Manager",
    finalRating: "-",
    status: "NOT_STARTED",
  },
  {
    name: "Manoj Deshmukh",
    id: "EMP019",
    role: "Data Engineer",
    quarter: "Q3",
    financialYear: "FY 2026-27",
    fromDate: "01-10-2026",
    toDate: "31-12-2026",
    assignedOn: "11-10-2026",
    assignedBy: "Manager",
    finalRating: "3.7",
    status: "SUBMITTED",
  },
  {
    name: "Ritu Verma",
    id: "EMP020",
    role: "Scrum Master",
    quarter: "Q3",
    financialYear: "FY 2026-27",
    fromDate: "01-10-2026",
    toDate: "31-12-2026",
    assignedOn: "12-10-2026",
    assignedBy: "Admin",
    finalRating: "4.8",
    status: "COMPLETED",
  },
  {
    name: "Varun Nair",
    id: "EMP021",
    role: "Cloud Engineer",
    quarter: "Q4",
    financialYear: "FY 2026-27",
    fromDate: "01-01-2027",
    toDate: "31-03-2027",
    assignedOn: "08-01-2027",
    assignedBy: "Manager",
    finalRating: "-",
    status: "IN_PROGRESS",
  },
  {
    name: "Kavya Murthy",
    id: "EMP022",
    role: "Product Analyst",
    quarter: "Q4",
    financialYear: "FY 2026-27",
    fromDate: "01-01-2027",
    toDate: "31-03-2027",
    assignedOn: "10-01-2027",
    assignedBy: "Manager",
    finalRating: "4.3",
    status: "COMPLETED",
  },
];

export const mockQuarterlyReviewAssignments: QuarterlyReviewAssignment[] = [
  {
    id: "rev-q1-2026",
    quarter: "Q1",
    financialYear: "FY 2026-27",
    assignedBy: "Manager",
    assignedDate: "01-Apr-2026",
    deadline: "15-Apr-2026",
    status: "submitted",
    submittedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(), // Submitted 4h ago - within 1-day window (ENABLED)
    description: "Complete your Q1 performance review focusing on deliverables, project milestones, and personal development goals.",
  },
  {
    id: "rev-q2-2026",
    quarter: "Q2",
    financialYear: "FY 2026-27",
    assignedBy: "Admin",
    assignedDate: "01-Jul-2026",
    deadline: "15-Jul-2026",
    status: "in_progress", // In progress - not submitted (DISABLED)
    description: "Quarterly review for Q2 product delivery and sprint milestones.",
  },
  {
    id: "rev-q4-2025",
    quarter: "Q4",
    financialYear: "FY 2025-26",
    assignedBy: "Manager",
    assignedDate: "01-Jan-2026",
    deadline: "15-Jan-2026",
    status: "reviewed",
    submittedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(), // Submitted 48h ago - expired 1-day window (DISABLED)
    description: "Annual cycle closing review for Q4 deliverables.",
  },
  {
    id: "rev-q3-2025",
    quarter: "Q3",
    financialYear: "FY 2025-26",
    assignedBy: "Manager",
    assignedDate: "01-Oct-2025",
    deadline: "15-Oct-2025",
    status: "reviewed",
    submittedAt: new Date(Date.now() - 120 * 3600 * 1000).toISOString(),
    description: "Mid-year review for Q3 achievements and engineering goals.",
  },
  {
    id: "rev-q2-2025",
    quarter: "Q2",
    financialYear: "FY 2025-26",
    assignedBy: "Admin",
    assignedDate: "01-Jul-2025",
    deadline: "15-Jul-2025",
    status: "reviewed",
    submittedAt: new Date(Date.now() - 210 * 3600 * 1000).toISOString(),
    description: "Q2 performance appraisal evaluation.",
  },
  {
    id: "rev-q1-2025",
    quarter: "Q1",
    financialYear: "FY 2025-26",
    assignedBy: "Manager",
    assignedDate: "01-Apr-2025",
    deadline: "15-Apr-2025",
    status: "reviewed",
    submittedAt: new Date(Date.now() - 300 * 3600 * 1000).toISOString(),
    description: "Q1 initial onboarding review and project alignment.",
  },
];

export const initialMockAccessRequests: AccessRequest[] = [];

export const initialReviewFormData: ReviewFormData = {
  // Step 1: Overview
  overview: "",
  roleSummary: "",
  keyResponsibilities: "",
  quarterHighlights: "",
  // Step 2: Achievements
  projectTitle: "",
  projectDescription: "",
  projectChallenge: "",
  majorAchievements: "",
  kpisMet: "",
  challengesOvercome: "",
  selfRatingAchievements: 0,
  // Step 3: Team Contribution
  collaborationDetails: "",
  mentorshipAssistance: "",
  peerSupport: "",
  teamRatings: {},
  // Step 4: Learning Goals
  learningGoals: "",
  skillsAcquired: "",
  certificationsOrCourses: "",
  nextQuarterLearningGoals: "",
  // Step 5: Company Environment
  workCultureFeedback: "",
  workLifeBalance: "",
  suggestionsForImprovement: "",
  companyEnvironmentRating: undefined,
  toolingAndResources: "",
  managementSupportRating: 0,
  // Step 6: Review & Final Comments
  overallSelfRating: 0,
  finalComments: "",
};

export const sampleCompletedReviewFormData: ReviewFormData = {
  // Step 1: Overview
  overview: "Frontend Developer focused on building and optimizing web applications. Delivered responsive UI components, collaborated with backend and design teams, and completed major modules ahead of schedule with zero critical bugs.",
  roleSummary: "Frontend Developer focused on building and optimizing web applications.",
  keyResponsibilities: "Delivering responsive UI components, collaborating with backend and design teams, code reviews.",
  quarterHighlights: "Completed major modules ahead of schedule with zero critical bugs.",
  // Step 2: Achievements
  projectTitle: "Worksphere Timesheet & Appraisal Platform",
  projectDescription: "Spearheaded the component library unification, streamlined workflow interfaces, and achieved 99% on-time delivery across quarterly deliverables.",
  projectChallenge: "Adapted to rapid requirements changes and resolved complex state synchronization challenges without delaying deployment milestones.",
  majorAchievements: "Spearheaded the component library unification and improved loading performance by 35%.",
  kpisMet: "Exceeded sprint velocity targets and achieved 99% on-time delivery across quarterly deliverables.",
  challengesOvercome: "Adapted to rapid requirements changes without delaying deployment milestones.",
  selfRatingAchievements: 4,
  // Step 3: Team Contribution
  collaborationDetails: "Actively participated in daily standups, sprint retrospectives, and pair-programming sessions.",
  mentorshipAssistance: "Assisted new teammates in onboarding with the codebase and local environment setup.",
  peerSupport: "Consistently reviewed pull requests within 2 hours of submission.",
  teamRatings: {
    communication: 5,
    ownership: 5,
    collaboration: 4,
    problemSolving: 5,
    leadership: 4,
    adaptability: 5,
  },
  // Step 4: Learning Goals
  learningGoals: "Advanced TypeScript patterns, Tailwind CSS v4 architecture, state management optimization. Completed Advanced Web Performance Optimization course. Explore Next.js server components and GraphQL integration.",
  skillsAcquired: "Advanced TypeScript patterns, Tailwind CSS v4 architecture, state management optimization.",
  certificationsOrCourses: "Completed Advanced Web Performance Optimization course.",
  nextQuarterLearningGoals: "Explore Next.js server components and GraphQL integration.",
  // Step 5: Company Environment
  workCultureFeedback: "The collaborative workspace is highly productive. The developer tools provided are excellent and help speed up development cycles.",
  workLifeBalance: "I feel highly aligned with the company's vision of delivering fast, reliable employee portals.",
  suggestionsForImprovement: "I feel highly aligned with the company's vision of delivering fast, reliable employee portals.",
  companyEnvironmentRating: 5,
  toolingAndResources: "Standard developer tooling provided is great. More design system documentation will help further.",
  managementSupportRating: 5,
  // Step 6: Review & Final Comments
  overallSelfRating: 4.5,
  finalComments: "Excited about the upcoming quarter goals and looking forward to taking ownership of bigger feature initiatives.",
};
