export enum LeaveNotificationStatus {
    PENDING = 'Pending',
    APPROVED = 'Approved',
    REJECTED = 'Rejected',
    REQUESTING_FOR_CANCELLATION = 'Requesting for Cancellation',
    CANCELLATION_APPROVED = 'Cancellation Approved',
    CANCELLATION_REJECTED = 'Cancellation Rejected',
    REQUESTING_FOR_MODIFICATION = 'Requesting for Modification',
    REQUEST_MODIFIED = 'Request Modified',
    MODIFICATION_APPROVED = 'Modification Approved',
    MODIFICATION_CANCELLED = 'Modification Cancelled',
    MODIFICATION_REJECTED = 'Modification Rejected',
    CANCELLATION_REVERTED = 'Cancellation Reverted',
    CANCELLED = 'Cancelled',
}

export enum LeaveRequestStatus {
    PENDING = 'Pending',
    APPROVED = 'Approved',
    REJECTED = 'Rejected',
    REQUESTING_FOR_CANCELLATION = 'Requesting for Cancellation',
    CANCELLATION_APPROVED = 'Cancellation Approved',
    CANCELLATION_REJECTED = 'Cancellation Rejected',
    REQUESTING_FOR_MODIFICATION = 'Requesting for Modification',
    REQUEST_MODIFIED = 'Request Modified',
    MODIFICATION_APPROVED = 'Modification Approved',
    MODIFICATION_CANCELLED = 'Modification Cancelled',
    MODIFICATION_REJECTED = 'Modification Rejected',
    CANCELLATION_REVERTED = 'Cancellation Reverted',
    CANCELLED = 'Cancelled',
}
export enum LeaveRequestType {
    APPLY_LEAVE = 'Apply Leave',
    LEAVE = 'Leave',
    WORK_FROM_HOME = 'Work From Home',
    WFH = 'WFH',
    CLIENT_VISIT = 'Client Visit',
    HALF_DAY = 'Half Day',
    COMP_OFF = 'Comp Off',
    HALF_DAY_LEAVE = 'Half Day Leave',
}
