export enum ResignationStatus {
  PENDING_MANAGER = "PENDING_MANAGER",
  MANAGER_APPROVED = "MANAGER_APPROVED",
  MANAGER_REJECTED = "MANAGER_REJECTED",
  PENDING_HR_ADMIN = "PENDING_HR_ADMIN",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  WITHDRAWN = "WITHDRAWN",
}
