import { ReviewFormData } from "../types/appraisal.types";

export const emptyReviewFormData: ReviewFormData = {
  overview: "",
  roleSummary: "",
  keyResponsibilities: "",
  quarterHighlights: "",
  projectTitle: "",
  projectDescription: "",
  projectChallenge: "",
  projects: [],
  projectAttachments: [],
  majorAchievements: "",
  challengesOvercome: "",
  selfRatingAchievements: 0,
  collaborationDetails: "",
  mentorshipAssistance: "",
  peerSupport: "",
  teamRatings: {},
  learningGoals: "",
  learningGoalItems: [],
  skillsAcquired: "",
  certificationsOrCourses: "",
  nextQuarterLearningGoals: "",
  workCultureFeedback: "",
  workLifeBalance: "",
  suggestionsForImprovement: "",
  toolingAndResources: "",
  companyEnvironmentRating: undefined,
  managementSupportRating: 0,
  overallSelfRating: 0,
  finalComments: "",
};
